<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-HFJIJJP" failures="0" tests="4" name="com.testng.Testng_Timeout" time="3.042" errors="1" timestamp="2022-08-14T00:07:19 GMT-07:00" skipped="0">
  <testcase classname="com.testng.Testng_Timeout" name="cMethod" time="1.016"/>
  <testcase classname="com.testng.Testng_Timeout" name="bMethod" time="1.002"/>
  <testcase classname="com.testng.Testng_Timeout" name="dMethod" time="0.001"/>
  <testcase classname="com.testng.Testng_Timeout" name="aMethod" time="1.023">
    <error message="Method com.testng.Testng_Timeout.aMethod() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.Testng_Timeout.aMethod() didn't finish within the time-out 1000
at app//org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:60)
at app//org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:41)
at java.base@11.0.16/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base@11.0.16/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@11.0.16/java.lang.Thread.run(Thread.java:834)
]]>
    </error>
  </testcase> <!-- aMethod -->
</testsuite> <!-- com.testng.Testng_Timeout -->
