<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-HFJIJJP" failures="1" tests="4" name="Default test" time="3.147" errors="0" timestamp="2022-08-30T12:35:50 IST">
  <testcase classname="com.testng.Testng_Timeout" name="aMethod" time="1.029">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.testng.Testng_Timeout.aMethod() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng.Testng_Timeout.aMethod() didn't finish within the time-out 1000
at java.base@11.0.16/java.util.concurrent.FutureTask.setException(FutureTask.java:247)
at java.base@11.0.16/java.util.concurrent.FutureTask.run(FutureTask.java:269)
at java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@11.0.16/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@11.0.16/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- aMethod -->
  <testcase classname="com.testng.Testng_Timeout" name="bMethod" time="1.011"/>
  <testcase classname="com.testng.Testng_Timeout" name="cMethod" time="1.011"/>
  <testcase classname="com.testng.Testng_Timeout" name="dMethod" time="0.002"/>
</testsuite> <!-- Default test -->
